INSERT INTO mydbspring.Customer (id, name, email, location) VALUES
(1, 'Aarav Mehta', 'aarav.mehta@example.com', 'Mumbai'),
(2, 'Emily Carter', 'emily.carter@example.com', 'New York'),
(3, 'Rohan Gupta', 'rohan.gupta@example.com', 'Delhi'),
(4, 'Sofia Martinez', 'sofia.martinez@example.com', 'Madrid'),
(5, 'Kabir Sharma', 'kabir.sharma@example.com', 'Bangalore'),
(6, 'Liam Johnson', 'liam.johnson@example.com', 'London'),
(7, 'Ananya Desai', 'ananya.desai@example.com', 'Ahmedabad'),
(8, 'Noah Kim', 'noah.kim@example.com', 'Seoul'),
(9, 'Isha Verma', 'isha.verma@example.com', 'Jaipur'),
(10, 'Lucas Brown', 'lucas.brown@example.com', 'Toronto'),
(11, 'Meera Nair', 'meera.nair@example.com', 'Kochi'),
(12, 'Ethan Smith', 'ethan.smith@example.com', 'Chicago'),
(13, 'Priya Reddy', 'priya.reddy@example.com', 'Hyderabad'),
(14, 'Olivia Nguyen', 'olivia.nguyen@example.com', 'Sydney'),
(15, 'Dev Patel', 'dev.patel@example.com', 'Pune');
